---
grails:
    profile: web
    codegen:
        defaultPackage: com.foysonis
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
   resources:
       cachePeriod: -1
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    format_sql: true
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory' 
        
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: 123456
#    password: Foison2016

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/foysonis_prodtest?zeroDateTimeBehavior=convertToNull
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/foysonis_test?autoReconnect=true&useSSL=false
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://173.194.249.54/foysonis_dev
#            url: jdbc:mysql://foysonisaurorainstance-cluster.cluster-ci8luflnlnok.us-west-2.rds.amazonaws.com/foysonis
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
company:
    billing:
        stripe:
            apiKey: "sk_test_njMYsHhAJuNpN0ZUottPU2RX"
---
grails:
    mail:
        username: "info"
        password: "infopassword"
        recipient: "pruthvin@foysonis.com"

---
grails:
    app:
      base:
#        url: "http://development.foysonis.com"
        url: "https://wms.foysonis.com"
    mail:
      logo:
        location: "/usr/local/tomcat7"
---
company:
    paymentPlan:
        individual:
            itemMaxLimit: 100
---
company:
    paymentPlan:
        individual:
            locationMaxLimit: 300
---
grails:
    login:
       backdoor:
           enabled: true
           username: "supportuser"
           password: '$2a$06$rdwbr/9Xrp8LVvAUEBE.Y.ZjgJ7BlZ6YGveSNuYSMiF5KLGj7Zmc6'

